services:
  db:
    image: mysql:9.3.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 5hfPYt
      MYSQL_USER: dimaster
      MYSQL_PASSWORD: 5hfPYt
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl_cert:/etc/nginx/ssl
    networks:
      - backend
    depends_on:
      - phpmyadmin

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
    external: true
