services:
  db:
    image: mysql:9.3.0
    container_name: mysql_db
    command: mysqld --sql_mode="" --character-set-server=utf8 --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PHP_UPLOAD_MAX_FILESIZE: 0
      PHP_POST_MAX_SIZE: 0
      UPLOAD_LIMIT: 0
    volumes:
      - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl_cert:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
    external: true
