services:
  nuxt:
    build:
      context: .
      dockerfile: ../../dockerfiles/node-nuxt.Dockerfile
    container_name: nuxt_app
    networks:
      - backend
    volumes:
      - ./app:/app
    environment:
      - HOST=0.0.0.0
    expose:
      - "3000"
      - "24678"

networks:
  backend:
    external: true